# Generated by Django 6.0.3 on 2026-04-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0002_account_alter_dish_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
